Multiple ski resorts
SW6-G6-2024/Ski-Planner-FE pull request #38
Opened 2024-04-17 09:16 UTC by Mafusn

2024-04-17 10:56 UTC, Jatewo requested changes
### Small changes

Could use some testing in cypress (just to ensure that the functionality is not broken later on)

Other than that a little change is requested (see the comment)

2024-04-17 12:05 UTC, Jatewo commented on src/components/Map/FeatureHandler.jsx
> +			{props.pistes && <GeoJSON key={`pistes-${props.key}`} data={props.pistes} style={{ ...setPisteColor, color: 'transparent', weight: 15 }} onEachFeature={addPisteDetails} />}
These keys should be removed. `props.key` will always return `undefined` and the key you need for leaflet to update can be defined in the FeatureHandler component in SkiMap.jsx only with the desired effect.

2024-04-17 12:05 UTC, Jatewo commented on src/components/Map/FeatureHandler.jsx
> +			{props.lifts && <GeoJSON key={`lifts-${props.key}`}data={props.lifts} style={{ ...setLiftStyle, color: 'transparent', weight: 15 }} onEachFeature={addLiftDetails} />}
See above

2024-04-17 12:05 UTC, Jatewo commented on src/components/Map/FeatureHandler.jsx
> +	key: PropTypes.string
See above

2024-04-17 12:54 UTC, MortenMunk requested changes
Please check comments by jatewo

2024-04-18 08:35 UTC, Jatewo approved these changes
LGTM 🥇

2024-04-18 08:37 UTC, Jatewo approved these changes

2024-04-18 08:40 UTC, MortenMunk approved these changes
LGTM

2024-04-18 08:42 UTC, merged